var that=this;function __skpm_run(r,t){that.context=t;var e=function(r){var t={};function e(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return r[n].call(a.exports,a,a.exports,e),a.l=!0,a.exports}return e.m=r,e.c=t,e.d=function(r,t,n){e.o(r,t)||Object.defineProperty(r,t,{enumerable:!0,get:n})},e.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},e.t=function(r,t){if(1&t&&(r=e(r)),8&t)return r;if(4&t&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(e.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&t&&"string"!=typeof r)for(var a in r)e.d(n,a,function(t){return r[t]}.bind(null,a));return n},e.n=function(r){var t=r&&r.__esModule?function(){return r.default}:function(){return r};return e.d(t,"a",t),t},e.o=function(r,t){return Object.prototype.hasOwnProperty.call(r,t)},e.p="",e(e.s="./src/cmd/validate-and-fix.js")}({"./src/artboards.js":
/*!**************************!*\
  !*** ./src/artboards.js ***!
  \**************************/
/*! exports provided: artboardRowsByName, autoAlignArtboards */function(r,t,e){"use strict";function n(r,t){return function(r){if(Array.isArray(r))return r}(r)||function(r,t){var e=[],n=!0,a=!1,o=void 0;try{for(var u,i=r[Symbol.iterator]();!(n=(u=i.next()).done)&&(e.push(u.value),!t||e.length!==t);n=!0);}catch(r){a=!0,o=r}finally{try{n||null==i.return||i.return()}finally{if(a)throw o}}return e}(r,t)||function(){throw new TypeError("Invalid attempt to destructure non-iterable instance")}()}function a(r){return r.layers.filter(function(r){return"Artboard"===r.type})}function o(r){return a(r).reduce(function(r,t){var e=parseInt(t.name.match(/\d+/)[0],10),n=String(e-e%100),a=r[n]||[];return a.push(t),r[n]=a.sort(function(r,t){return r.frame.x-t.frame.x}),r},{})}function u(r){var t=function(r){for(var t=a(r),e=[],o=0;o<t.length;o++)parseInt(t[o].name,10)%100==0&&e.push(t[o]);e.sort(function(r,t){return r.frame.y-t.frame.y});for(var u={},i=0;i<e.length;i++){var c=(100*(i+1)).toString();u[c]=[e[i]]}for(var s=Object.entries(u).map(function(r){var t=n(r,2);return[t[0],t[1][0].frame.y]}),f=function(r){var a=t[r];if(e.some(function(r){return r.id===a.id}))return"continue";var o=a.frame.y,i=void 0,c=1/0,f=!0,l=!1,d=void 0;try{for(var v,m=s[Symbol.iterator]();!(f=(v=m.next()).done);f=!0){var y=n(v.value,2),b=y[0],g=y[1],p=Math.abs(o-g);p<c&&(i=b,c=p)}}catch(r){l=!0,d=r}finally{try{f||null==m.return||m.return()}finally{if(l)throw d}}u[i].push(t[r])},l=0;l<t.length;l++)f(l);return Object.values(u).forEach(function(r){return r.sort(function(r,t){return r.frame.x-t.frame.x})}),u}(r),e=Object.keys(t).sort(function(r,t){return parseInt(r,10)-parseInt(t,10)}),o=0,u=!0,i=!1,c=void 0;try{for(var s,f=e[Symbol.iterator]();!(u=(s=f.next()).done);u=!0){var l=s.value,d=t[l],v=0,m=1e3,y=0,b=!0,g=!1,p=void 0;try{for(var h,j=d[Symbol.iterator]();!(b=(h=j.next()).done);b=!0){var x=h.value;x.moveToFront();var O=parseInt(l,10)+y;x.name=O.toString(),x.frame.x=v,x.frame.y=o;var S=x.frame.height+100;S>m&&(m=S+(500-S%500)),v+=500,y++}}catch(r){g=!0,p=r}finally{try{b||null==j.return||j.return()}finally{if(g)throw p}}o+=m}}catch(r){i=!0,c=r}finally{try{u||null==f.return||f.return()}finally{if(i)throw c}}}e.r(t),e.d(t,"artboardRowsByName",function(){return o}),e.d(t,"autoAlignArtboards",function(){return u})},"./src/cmd/validate-and-fix.js":
/*!*************************************!*\
  !*** ./src/cmd/validate-and-fix.js ***!
  \*************************************/
/*! exports provided: default */function(r,t,e){"use strict";e.r(t),e.d(t,"default",function(){return c});var n=e(/*! sketch */"sketch"),a=e(/*! ../utils */"./src/utils.js"),o=e(/*! ../validators */"./src/validators.js"),u=e(/*! ../artboards */"./src/artboards.js"),i=e(/*! ../wip-rows */"./src/wip-rows.js");function c(){var r=Object(n.getSelectedDocument)(),t=Object(o.validateAll)(r);if(t.success){var e=Object(a.getMasterPage)(r);Object(u.autoAlignArtboards)(e),Object(i.markWipRows)(r,e)}else n.UI.message("‼️ ".concat(t.message))}},"./src/utils.js":
/*!**********************!*\
  !*** ./src/utils.js ***!
  \**********************/
/*! exports provided: getMasterPage */function(r,t,e){"use strict";function n(r){return r.pages.find(function(r){return"Master"===r.name})}e.r(t),e.d(t,"getMasterPage",function(){return n})},"./src/validators.js":
/*!***************************!*\
  !*** ./src/validators.js ***!
  \***************************/
/*! exports provided: validateMasterPresence, validatePageNames, validateArtboardNames, default, validateAll */function(r,t,e){"use strict";e.r(t),e.d(t,"validateMasterPresence",function(){return a}),e.d(t,"validatePageNames",function(){return o}),e.d(t,"validateArtboardNames",function(){return u}),e.d(t,"validateAll",function(){return c});var n=e(/*! ./utils */"./src/utils.js");function a(r){return Object(n.getMasterPage)(r)?{success:!0}:{success:!1,message:"Missing page 'Master'"}}function o(r){for(var t=["Master","Symbols"],e=r.pages,n=0;n<e.length;n++){var a=e[n].name;if(-1===t.indexOf(a))return{success:!1,message:"Invalid page name '".concat(a,"'")}}return{success:!0}}function u(r){for(var t=Object(n.getMasterPage)(r).layers.filter(function(r){return"Artboard"===r.type}),e={},a=0;a<t.length;a++){var o=t[a].name;if(e[o])return{success:!1,message:"Duplicate artboard name '".concat(o,"'")};if(e[o]=o,!o.match(/^\d{3,4}(\.[A-Z]{1,2})?/))return{success:!1,message:"Invalid artboard name '".concat(o,"'")}}return{success:!0}}var i=[a,o,u];function c(r){for(var t=0;t<i.length;t++){var e=(0,i[t])(r);if(!e.success)return e}return{success:!0}}t.default=i},"./src/wip-rows.js":
/*!*************************!*\
  !*** ./src/wip-rows.js ***!
  \*************************/
/*! exports provided: markWipRows */function(r,t,e){"use strict";e.r(t),e.d(t,"markWipRows",function(){return i});var n=e(/*! ./artboards */"./src/artboards.js"),a=/\bWIP$/,o="#000000FF",u="#F43951FF";function i(r,t){for(var e=function(r,t){var e=r.getSymbols().find(function(r){return r.name.match(a)});if(!e)return console.log("Couldn't find WIP symbol"),[];var n=[],o=!0,u=!1,i=void 0;try{for(var c,s=e.getAllInstances()[Symbol.iterator]();!(o=(c=s.next()).done);o=!0){var f=c.value,l=f.getParentPage(),d=f.getParentArtboard();if(d&&l.isEqualTo(t)){var v=parseInt(d.name,10),m=(v-v%100).toString();-1===n.indexOf(m)&&n.push(m)}}}catch(r){u=!0,i=r}finally{try{o||null==s.return||s.return()}finally{if(u)throw i}}return n}(r,t),i=Object(n.artboardRowsByName)(t),c=Object.keys(i),s=0;s<c.length;s++){var f=c[s],l=i[f][0];e.includes(f)?l.background.color=u:l.background.color===u&&(l.background.color=o)}}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(r,t){r.exports=require("sketch")}});"default"===r&&"function"==typeof e?e(t):e[r](t)}that.onRun=__skpm_run.bind(this,"default");